apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centrifugo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jhorman967/grafana.git
    targetRevision: HEAD
    path: centrifugo
  destination:
    server: https://kubernetes.default.svc #internal name de kubernetes cluster service
    namespace: centrifugo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true