##################################################
###      Variables for the Prometheus          ###  
##################################################
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 3h
        receiver: 'msteams'
      receivers:
        - name: 'msteams'
          webhook_configs:
            - url: 'https://mdcloudps.webhook.office.com/webhookb2/36374362-6fb7-4875-88c3-5465a33288e0@33d2928a-e889-4d75-8b16-ff1cb54ae031/IncomingWebhook/a5297bf0b33e49bdb173f7fc1a2542f4/afd3765f-3b39-4b18-b114-51b0a684804e/V2xbmy1TCXU4NfUqh6NDqp4myKzJc6QRb2nj7rSNN8lLY1'
              send_resolved: true

  grafana:
    enabled: false  


##################################################
###         Variables for the Grafana          ###  
##################################################
grafana:
  admin:
    existingSecret: grafana-admin
    passwordKey: admin-password
    userKey: admin-user


  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-read:3100
          isDefault: true
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated.monitoring.svc.cluster.local:9090
          editable: true  

  persistence:
    enabled: false
    storageClassName: standard
    size: 5Gi

  service:
    type: NodePort
  


  

##################################################
###         Variables for the loki             ###  
##################################################

loki:
  # Deployment mode: SingleBinary (simple), SimpleScalable (medium), Distributed (large)
  deploymentMode: SimpleScalable
  loki:
    auth_enabled: false
    storage:
      bucketNames:
        chunks: bucketprueba-jh
        ruler: loki-ruler
        admin: loki-admin
      s3:
        region: us-east-1
        access_key_id: AKIARLP5O743HTPL4BGL
        secret_access_key: 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
        s3forcepathstyle: false
        insecure: false
      
    commonConfig:
      replication_factor: 1  

    useTestSchema: false
    persistence:
      enabled: true #Permite la eliminacion automatica del persistence volumen
      storageClassName: standard
      size: 5Gi

    schemaConfig:
      configs:
        - from: "2025-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h


  
  rulerConfig:
    alertmanager_url: http://observability-stack-kube-p-alertmanager.monitoring.svc.cluster.local:9093
    wal:
      dir: /var/loki/ruler-wal
       
  
  # secrets:
  #   s3:
  #     name: loki-s3-credentials
  #     keys:
  #       access_key_id: access_key_id
  #       secret_access_key: secret_access_key
  
  singleBinary:
    replicas: 0

  test:
    enabled: false

  # -- util para centralizar todo las conexion de no en sigle binary
  gateway:
    enabled: false
  #componenete replica don't necesary for singleBinary
  write:
    replicas: 1
    affinity:
      podAntiAffinity: {}
  read:
    replicas: 1
    affinity:
      podAntiAffinity: {}
  backend:
    replicas: 1
    affinity:
      podAntiAffinity: {}


  limits_config:
    allow_structured_metadata: true

##se debe modificar al subir a produccion para usar S32
  # schemaConfig:
  #   configs:
  #     - from: "2024-01-01"
  #       store: boltdb-shipper
  #       object_store: s3
  #       schema: v11
  #       index:
  #         prefix: index_
  #         period: 24h

  # storage:
  #   type: s3



##################################################
###       Variables for the promtail           ###  
##################################################

promtail:
  config:
    clients:
      - url: http://loki-write.monitoring.svc.cluster.local:3100/loki/api/v1/push


    snippets:
      pipelineStages:
        - docker: {}
        - cri: {}

