apiVersion: v1
kind: Secret
metadata:
  name:  loki-s3-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access_key_id: "AKIARLP5O743GCFN446L"
  secret_access_key: "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"



